"""db setup

Revision ID: 6457f04f4438
Revises: 
Create Date: 2025-04-10 12:59:09.722635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6457f04f4438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('image_name', sa.String(length=100), nullable=False),
    sa.Column('image_large_binary', sa.LargeBinary(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('image_hash')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email_id', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_prompt', sa.String(length=4098), nullable=False),
    sa.Column('response', sa.String(length=4098), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('suggestion', sa.String(length=300), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash')
    )
    op.create_table('saved_chat',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('userprompt', sa.String(length=4098), nullable=False),
    sa.Column('response', sa.String(length=4098), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_chat')
    op.drop_table('feedback')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###
