"""users

Revision ID: 7fa100f91326
Revises: acc7f0858f47
Create Date: 2025-04-21 11:49:40.447637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa100f91326'
down_revision = 'acc7f0858f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('feedback_image_hash_key', type_='unique')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('images_image_hash_key', type_='unique')

    with op.batch_alter_table('saved_chat', schema=None) as batch_op:
        batch_op.drop_constraint('saved_chat_image_hash_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.drop_constraint('users_email_id_key', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_email_id_key', ['email_id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('password')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('saved_chat', schema=None) as batch_op:
        batch_op.create_unique_constraint('saved_chat_image_hash_key', ['image_hash'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_unique_constraint('images_image_hash_key', ['image_hash'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_unique_constraint('feedback_image_hash_key', ['image_hash'])

    # ### end Alembic commands ###
